export const GENERATE_PASSWORD = "GENERATE_PASSWORD";
export const CROP_BOX = "CROP_BOX";
export const VOXEL_GRID = "VOXEL_GRID";
export const STATISTICAL_REMOVAL = "STATISTICAL_REMOVAL";
export const NORMAL_ESTIMATION = "NORMAL_ESTIMATION";
export const REESCALE = "REESCALE";
export const CENTRALIZATION = "CENTRALIZATION";
export const ALIGNMENT = "ALIGNMENT";